# Destroy messages, users and channels (in that order)
Message.destroy_all if Rails.env.development?
User.destroy_all if Rails.env.development?
Channel.destroy_all if Rails.env.development?

# Create some channels (general, paris, react for instance)
Channel.create!(name: "general")
Channel.create!(name: "paris")
Channel.create!(name: "react")
Channel.all.each { |channel| puts "#{channel.name} created" }

# Create some users (needs email / password)
User.create!(email: "boris@example.fr", password: "123456")
User.create!(email: "seb@example.fr", password: "123456")
User.create!(email: "fab@example.fr", password: "123456")
User.all.each { |user| puts "#{user.email} created" }

# Create some messages in several channels.
Message.create!(content: "HACK THE CRISIS! We are living through weird times - the kind of times our children and grandchildren will read about in history books (if mankind makes it that far). We've been quarantined for a while now, and it can be frustrating to think there isn't much else we can do to help overcome this, aside from staying home:house:. But wait...maybe THERE IS SOMETHING WE CAN DO :thinking_face:. How about... a 48h online hackathon :space_invader: to develop open-source prototypes geared towards solving the most pressing problems generated by the COVID-19 crisis 🦠? Hack the Crisis Denmark will happen between the 3rd and 5th of April :calendar: and we're looking for people from all walks of life to contribute (but we surely need plenty of Developers!!!) — everyone is affected, and so everyone can help make a difference! :muscle: ", channel: Channel.all[0], user: User.all[0])

Message.create!(content: "Help where you can! Folding@home (FAH or F@h) is a distributed computing project for simulating protein dynamics, including the process of protein folding and the movements of proteins implicated in a variety of diseases. It brings together citizen scientists who volunteer to run simulations of protein dynamics on their personal computers. Insights from this data are helping scientists to better understand biology, and providing new opportunities for developing therapeutics.", channel: Channel.all[0], user: User.all[1])

Message.create!(content: "Hi guys, any idea where/why the lectures for Stripe  payments and for Mailers disappeared?", channel: Channel.all[0], user: User.all[2])

Message.create!(content: "Hello, I am making a website for an artist with some pictures https://la-fin.herokuapp.com/ I am wondering which web host should I use to have the best speed with the smallest price. Any ideas? Is it better to use a free one as heroku with Cloudinary?", channel: Channel.all[0], user: User.all[0])

Message.create!(content: "COVID-19 GLOBAL HACKATHON CALL FOR HELP :exclamation: Can you help on 2 projects to help fight Covid19 :covid19: this weekend?", channel: Channel.all[0], user: User.all[1])

Message.create!(content: "Hello ! J'espère que vous allez tous bien, que vous êtes safe et à la maison :slightly_smiling_face: Quelqu'un sait-il si un channel pour le batch du 6 avril a été ouvert ? et plus précisément qui sont nos interlocuteurs si besoin dans la complétion du prep work ? (l'idée est de ne pas polluer les autres channels à tout va :slightly_smiling_face: ) Merci & bon courage à tous !", channel: Channel.all[1], user: User.all[2])

Message.create!(content: "Hello, pour vous aider en ces temps difficiles, vous pouvez retrouvez des applications qui sont passées gratuites le temps du confinement, elles sont checkées par le gouvernement: https://www.economie.gouv.fr/coronavirus-offre-services-numeriques#", channel: Channel.all[1], user: User.all[0])

Message.create!(content: "Avec @Pilou (Bordeaux), @Elsa (Paris) et d'autres citoyens bénévoles on lancé le projet sosequipements.fr lors du hackathon HackLaCrise. La plateforme (mise en ligne hier) a pour but de redistribuer les équipements de protection et matériels médicaux. :pray:On a besoin de vous pour faire tourner afin de trouver autant de proposition d’équipements que de demandes et les faire matcher !:link: Merci d’avance !!!:clap: ", channel: Channel.all[1], user: User.all[1])

Message.create!(content: "Hello, :javascript: JavaScript champions! Did anyone here ever manage to scrape a website from an app’s front-end without using a 3rd party CORS proxy?", channel: Channel.all[2], user: User.all[2])

Message.create!(content: "Anyone know of an :angular: Angular2 package or service for searching all of  the content on the site? (I'm not interested in paying much for a commercial service as the search traffic would be fairly low.) Thx", channel: Channel.all[2], user: User.all[0])

Message.create!(content: "Hey I was wondering if anyone had any experience with video call integration in a web app. So far I’ve stumbled upon WebRTC and am trying to understand it’s js.", channel: Channel.all[2], user: User.all[1])

Message.all.each { |message| puts "Message #{message.id} of #{message.user.email} in channel #{message.channel.name} created" }
